editor_settings:
    figure_header: 'no'
    footer_log: 'yes'

default_sizes:
    board_grid_rows: 18
    board_grid_cols: 10
    main_window_rows: 16
    main_window_cols: 7
    board_grid_height: '580px'
    menu_element_description: '120px'

plot_parameters:
    grid: 'no'
    aspect: 'auto'
    height: 5.2
    width: 6

main_function:
    linestyle: 'solid'
    linewidth: 2
    color: '#1f77b4'
    default: linear

derivative:
    linestyle: 'solid'
    linewidth: 1.5
    max_derivative: 3
    colors:
        - '#ff8647'
        - '#39ff33'
        - '#7b6cef'

asymptote:
    linestyle: 'dashed'
    linewidth: 1
    color: '#000000'

zero_points:
    markersize: 6
    color: '#000000'
    methods: # allowed: newton, bisect, brentq, brenth, ridder, toms748
        - newton
        - brentq
        - brenth
        - bisect
        - toms748
        - ridder

refinement:
    values:
        - 10
        - 100
        - 1000
        - 10000

default_functions:
    linear:
        name: 'y = x'
        formula: 'lambda x: x'
        linspace: 'np.linspace(-10, 10, 101)'
        latex: 'r"$y = x$"'
    quadratic:
        name: 'y = x^2'
        formula: 'lambda x: np.power(x, 2)'
        linspace: 'np.linspace(-10, 10, 101)'
        latex: 'r"$y = x^2$"'
    cubic:
        name: 'y = x^3'
        formula: 'lambda x: np.power(x, 3)'
        linspace: 'np.linspace(-10, 10, 101)'
        latex: 'r"$y = x^3$"'
    sqrt:
        name: 'y = sqrt x'
        formula: 'lambda x: np.sqrt(x)'
        linspace: 'np.linspace(0.1, 20, 101)'
        latex: 'r"$y = \sqrt{x}$"'
    e:
        name: 'y = e^x'
        formula: 'lambda x: np.exp(x)'
        linspace: 'np.linspace(-10, 10, 101)'
        latex: 'r"$y = e^x$"'
    log:
        name: 'y = log x'
        formula: 'lambda x: np.log(x)'
        linspace: 'np.linspace(0.1, 10.1, 101)'
        latex: 'r"$y = \log\ x$"'
    sin:
        name: 'y = sin x'
        formula: 'lambda x: np.sin(x)'
        linspace: 'np.linspace(-2 * np.pi, 4 * np.pi, 12 * 10 + 1)'
        latex: 'r"$y = \sin\ x$"'
        xticks_data:
            xticks: '[n * np.pi / 2 for n in range(-4, 8 + 1)]'
            xticklabels: '[smart_ticklabel(n, r"\pi", 2) for n in range(-4, 8 + 1)]'
    cos:
        name: 'y = cos x'
        formula: 'lambda x: np.cos(x)'
        linspace: 'np.linspace(-2 * np.pi, 4 * np.pi, 12 * 10 + 1)'
        latex: 'r"$y = \cos\ x$"'
        xticks_data:
            xticks: '[n * np.pi / 2 for n in range(-4, 8 + 1)]'
            xticklabels: '[smart_ticklabel(n, r"\pi", 2) for n in range(-4, 8 + 1)]'
