editor_settings:
  interactive_elements: 'no'
  footer_log: 'yes'

default_sizes:
  board_grid_rows: 18
  board_grid_cols: 10
  main_window_rows: 15
  main_window_cols: 7
  board_grid_height: '580px'
  menu_element_description: '100px'

plot_parameters:
  grid: 'no'
  aspect: 'auto'
  height: 5
  width: 6.8

main_function:
  linestyle: 'solid'
  linewidth: 1.8
  color: '#1f77b4'
  default:
    name: 'x^2'
    formula: 'lambda x: np.power(x, 2)'
    derivatives: # order matters...
      - 'lambda x: 2*x'
    linspace: 'np.linspace(-10, 10, 101)'
    latex: 'r"$f(x) = x^2$"'

derivative:
  linestyle: 'solid'
  linewidth: 1.5
  max_derivative: 3
  colors: # number of colors must match 'max_derivative'
    - '#ff8647'
    - '#c01e58'
    - '#7b6cef'

asymptote:
  linestyle: 'dashed'
  linewidth: 1
  color: '#000000'

zero_points:
  markersize: 6
  color: '#000000'
  iterations: 50
  round: 10

extremes:
  markersize: 6
  color: '#e32400'

inflex_points:
  markersize: 6
  color: '#77bb40'

increasing:
  linestyle: 'solid'
  linewidth: 2
  color: '#33ff4c'

decreasing:
  linestyle: 'solid'
  linewidth: 2
  color: '#E34A27'

convex:
  linestyle: 'solid'
  linewidth: 2
  color: '#2B2466'

concave:
  linestyle: 'solid'
  linewidth: 2
  color: '#F1C344'

refinement_x:
  values:
    - 'pôvodné'
    - '10'
    - '100'
    - '1000'
    - '10000'
    - '100000'
    - '1000000'

refinement_y:
  values:
    - '-100'
    - '-10'
    - 'pôvodné'
    - '10'
    - '100'