editor_settings:
  interactive_elements: 'no'
  footer_log: 'yes'
  round:
    from: 0
    to: 12
    default: 6

default_sizes:
  board_grid_rows: 20
  board_grid_cols: 25
  main_window_rows: 17
  main_window_cols: 17
  board_grid_height: '580px'
  menu_element_description: '100px'

plot_parameters:
  grid: 'no'
  aspect: 'auto'
  height: 5
  width: 6.2

main_function:
  linestyle: 'solid'
  linewidth: 1.8
  color: '#1f77b4'
  default:
    name: 'x^2'
    formula: 'lambda x: np.power(x, 2)'
    derivatives: # order matters...
      - 'lambda x: 2*x'
    linspace: 'np.linspace(-10, 10, 101)'

derivative:
  linestyle: 'solid'
  linewidth: 1.5
  user_max: 3
  colors: # number of colors must match 'user_max'
    - '#ff8647'
    - '#c01e58'
    - '#7b6cef'

asymptote:
  linestyle: 'dashed'
  linewidth: 1
  color: '#000000'

zero_points:
  marker: 'o'
  markersize: 7
  color: '#000000'
  iterations: 50

extremes:
  marker: 'o'
  markersize: 7
  color: '#e32400'

inflex_points:
  marker: 'o'
  markersize: 7
  color: '#77bb40'

increasing:
  linestyle: 'solid'
  linewidth: 2
  color: '#33ff4c'

decreasing:
  linestyle: 'solid'
  linewidth: 2
  color: '#E34A27'

concave_up:
  linestyle: 'solid'
  linewidth: 2
  color: '#2B2466'

concave_down:
  linestyle: 'solid'
  linewidth: 2
  color: '#F1C344'

refinement_x:
  values:
    - 'pôvodné'
    - '10'
    - '100'
    - '1000'
    - '10000'
    - '100000'
    - '1000000'